### ISSUE TITLE
[feature request] GM Only Mode

### ISSUE THREAD

**Issue by Heljspe** [SpectralCiphers/safety-tools#3]
Have installed and intend to use this, but we have quite a few shy players who would be mortified that this popped up on EVERYONEs screen (even though it doesn't say WHO triggered it, thank goodness). 
Could there be an option for it to be privately triggered for just the GM, who can then steer the story as necessary? 
Maybe with both a public and private STOP (because thats a pretty urgent one and if its another player saying something....)?

**Comment by sattvik** [comment]
I think this has been addressed since v0.3.0.
