### ISSUE TITLE
Module does not work on new v9 FoundryVTT

### ISSUE THREAD

**Issue by neovatar** [SpectralCiphers/safety-tools#4]
Unfortunately, the module does not work any  longer with the new FoundryVTT v9. The map stays black and toolbar does not work.

With just this module active:

```
foundry.js:316 TypeError: Failed to render WebGL canvas: Cannot read properties of undefined (reading 'safety-tools')
    at Canvas._createGroups (foundry.js:19735)
    at Canvas.initialize (foundry.js:19636)
    at Game.initializeCanvas (foundry.js:5614)
    at async Game.setupGame (foundry.js:5484)
    at async Game._initializeGameView (foundry.js:6434)
    at async Game.initialize (foundry.js:5380)
```

**Comment by Artish357** [comment]
I was able to hack it to work by changing
https://github.com/SpectralCiphers/safety-tools/blob/f40ea52ed7a8443c43d0c43ac9cd98ec96dc959f/src/index.ts#L190
to this in in my local js file
```JS
CONFIG.Canvas.layers[MODULE_NAME] = {
    "group": "interface",
    "layerClass": SafetyToolsLayer
};
```
Probably not how you fix it for real!

**Comment by neovatar** [comment]
Thanks @Artish357 - that was the missing piece.

I created a PR for @sattvik

**Comment by neovatar** [comment]
reopened issue again, since the merge in my fork triggered closure
